export const testimonials = [
  {
    id: "abeer",
    youtubeId: "I1Z6BsYjHXk",
    isShort: true,
    name: "Preet Rajwade",
    exam: "",
    college: "",
    score: "",
    duration: "0:45",
    title: "Hear It From Our Achievers",
    quote: "KATexpert gave me the structure I needed to convert my CAT dream into reality.",
  },
  {
    id: "khushi",
    youtubeId: "RUch3M7DeR0",
    isShort: true,
    name: "Vanshita Patel",
    exam: "",
    college: "",
    score: "",
    duration: "0:52",
    title: "Why Students Trust KATexpert",
    quote: "The mentorship here is unmatched — every doubt cleared, every step guided.",
  },
  {
    id: "arpit",
    youtubeId: "QxO2NxT7BxA",
    isShort: true,
    name: "Arpit",
    exam: "CET",
    college: "",
    score: "",
    duration: "1:02",
    title: "Arpit's CET Success Story",
    quote: "From average scores to a top JBIMS seat — the KATexpert grind changed everything.",
  },
  {
    id: "tanishq",
    youtubeId: "7WWzJHTznMs",
    isShort: true,
    name: "Jay",
    exam: "MBA",
    college: "",
    score: "",
    duration: "0:48",
    title: "Get the Guidance You Deserve",
    quote: "The faculty knows exactly where students struggle and how to fix it fast.",
  },
  {
    id: "atharv",
    youtubeId: "D2MOUroto0k",
    isShort: true,
    name: "Atharv",
    exam: "CET",
    college: "",
    score: "",
    duration: "0:55",
    title: "Atharv's CET Success Story",
    quote: "Consistent mocks and honest feedback — that's the KATexpert formula.",
  },
  {
    id: "why-love",
    youtubeId: "yYUONg1f-Sw",
    isShort: true,
    name: "Darshan",
    exam: "",
    college: "",
    score: "",
    duration: "0:40",
    title: "Why Students Love KATexpert",
    quote: "It stopped feeling like coaching and started feeling like a second home.",
  },
  {
    id: "rupali",
    youtubeId: "e_e0P-FHeJ8",
    isShort: true,
    name: "Rupali",
    exam: "IELTS",
    college: "",
    score: "",
    duration: "0:58",
    title: "Rupali's Success Story",
    quote: "Personal attention that big institutes just can't offer.",
  },
  {
    id: "comfort",
    youtubeId: "5QxsWC1Jkz4",
    isShort: true,
    name: "Shrimant",
    exam: "",
    college: "",
    score: "",
    duration: "0:42",
    title: "Why Students Feel Comfortable Here",
    quote: "The environment lets you ask the silliest question without hesitation.",
  },
  {
    id: "guidance",
    youtubeId: "Ns_tSPuYHAA",
    isShort: true,
    name: "Radhika",
    exam: "CET",
    college: "",
    score: "",
    duration: "0:47",
    title: "Success Starts with the Right Guidance",
    quote: "Cracked my first campus interview thanks to KATexpert's CRT program.",
  },
  {
    id: "kasak",
    youtubeId: "5-BL0hHz0IQ",
    isShort: true,
    name: "Kasak",
    exam: "",
    college: "",
    score: "",
    duration: "1:05",
    title: "Kasak's Math Transformation Story",
    quote: "Went from fearing quant to topping quant sectionals — literally.",
  },
  {
    id: "yashi",
    youtubeId: "rjA_MCLB2UM",
    isShort: true,
    name: "Yashi",
    exam: "CAT",
    college: "",
    score: "",
    duration: "0:50",
    title: "Yashi's CAT Preparation Strategy",
    quote: "Strategy sessions with mentors saved months of misdirected effort.",
  },
  {
    id: "krish",
    youtubeId: "F1B35HJKOpM",
    isShort: true,
    name: "Krish Sir",
    exam: "CAT",
    college: "",
    score: "",
    duration: "1:10",
    title: "CAT 2025 Exam Pattern & Strategy",
    quote: "Krish Sir breaks down CAT into a plan you can actually execute.",
  },
  {
    id: "arumita",
    youtubeId: "4F12hXxDKr4",
    isShort: true,
    name: "Arumita Ma'am",
    exam: "IPMAT",
    college: "",
    score: "",
    duration: "0:59",
    title: "IPMAT Tips You Can't Miss",
    quote: "Every IPMAT trick condensed into actionable classroom insights.",
  },
  {
    id: "hosted-4",
    videoUrl: "https://katexperts.com/wp-content/uploads/2025/08/WhatsApp-Video-2025-08-06-at-12.40.25-PM-1.mp4",
    isShort: true,
    name: "Seminar",
    exam: "CAT",
    college: "",
    score: "",
    duration: "0:25",
    title: "Student Review",
    quote: "Personalized attention and strategy sessions that improved my performance.",
  },
  {
    id: "hosted-5",
    videoUrl: "https://katexperts.com/wp-content/uploads/2025/08/WhatsApp-Video-2025-08-06-at-12.40.44-PM-1.mp4",
    isShort: true,
    name: "Arumita mam",
    exam: "MCA CET",
    college: "",
    score: "",
    duration: "0:30",
    title: "Student Review",
    quote: "Extremely supportive teachers and standard study material.",
  },
  {
    id: "varc",
    youtubeId: "Q-87AntscUw",
    isShort: false,
    name: "Featured Masterclass",
    exam: "CAT",
    college: "All Programs",
    score: "Featured",
    duration: "12:14",
    title: "VARC Strategy 2025 — Attempt & Exam Pattern",
    quote: "A masterclass on VARC strategy and attempt planning that changes how you approach the section.",
  },
];

export const categories = ["All", "CAT", "IPMAT", "MBA CET", "MCA CET", "CRT"];
